#!/bin/bash

# This script deletes the "certs", "keys" and "reqs" folders generated by the
# other scripts in this folder, along all files inside them

cd "$(dirname "$0")"

rm -rf ../certs/
rm -rf ../keys/
rm -rf ../reqs/